### ISSUE TITLE
literówka

### ISSUE THREAD

**Issue by St4rBoyek** [XIIIG/CS-GO-Config#6]
Hejka, ogólnie chyba jest literówka:
"ud_playercount_pos              "0"       // Miejsce wyświetlania żywych graczy w HUD. 0 - góra, 1 - dół." - linijka 112
powinno być chyba **hud_playercount_pos**.
![image](https://user-images.githubusercontent.com/40685883/115961016-d23bde80-a514-11eb-8858-39d47531fce5.png)

**Comment by XIIIG** [comment]
Trochę zaspałem, ale już poprawione - dzięki.
